---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/categories":
    get:
      summary: 카테고리 정보를 가져옵니다.
      tags:
      - Categories
      responses:
        '200':
          description: 카테고리 정보를 가져옵니다.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    icon:
                      type: string
                  required:
                  - id
                  - name
                  - icon
        '404':
          description: 카테고리를 찾을 수 없습니다.
  "/contents/popular":
    get:
      summary: 리뷰가 5개 이상인 컨텐츠 정보를 가져옵니다.
      tags:
      - Contents
      responses:
        '200':
          description: 리뷰가 5개 이상인 컨텐츠를 가져옵니다.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    subtitle:
                      type: string
                    description:
                      type: string
                    imagePath:
                      type: string
                    content:
                      type: string
                    clover:
                      type: integer
                    reviews_count:
                      type: integer
                  required:
                  - id
                  - title
                  - imagePath
                  - content
                  - clover
        '404':
          description: 리뷰가 5개 이상인 컨텐츠가 없습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  "/contents/category/{category_id}/reviews":
    get:
      summary: 카테고리별 인기 많은 순으로 컨텐츠를 가져옵니다.
      tags:
      - Contents
      parameters:
      - name: category_id
        in: path
        description: Category ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: contents found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    subtitle:
                      type: string
                    description:
                      type: string
                    imagePath:
                      type: string
                    content:
                      type: string
                    clover:
                      type: integer
                    review_count:
                      type: integer
                  required:
                  - id
                  - title
                  - subtitle
                  - description
                  - imagePath
                  - content
                  - clover
                  - review_count
        '404':
          description: category not found
  "/contents/{id}":
    get:
      summary: 특정 컨텐츠 정보를 가져옵니다.
      tags:
      - Contents
      parameters:
      - name: id
        in: path
        description: Content ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: content found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  subtitle:
                    type: string
                  description:
                    type: string
                  imagePath:
                    type: string
                  content:
                    type: string
                  clover:
                    type: integer
                required:
                - id
                - title
                - imagePath
                - content
                - clover
        '404':
          description: content not found
  "/contents/reviews":
    get:
      summary: 전체 컨텐츠를 리뷰 수 기준으로 가져옵니다.
      tags:
      - Contents
      responses:
        '200':
          description: 정렬된 컨텐츠를 가져옵니다.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    subtitle:
                      type: string
                    description:
                      type: string
                    imagePath:
                      type: string
                    content:
                      type: string
                    clover:
                      type: integer
                    review_count:
                      type: integer
                  required:
                  - id
                  - title
                  - subtitle
                  - description
                  - imagePath
                  - content
                  - clover
                  - review_count
        '404':
          description: 콘텐츠가 없습니다.
  "/my_infos":
    get:
      summary: 모든 my_infos 조회
      tags:
      - MyInfos
      responses:
        '200':
          description: 모든 my_infos 조회
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/MyInfo"
    post:
      summary: my_info 생성
      tags:
      - MyInfos
      parameters: []
      responses:
        '201':
          description: my_info 생성
        '422':
          description: 잘못된 요청일 경우 오류 메시지를 반환
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/MyInfo"
  "/my_infos/{id}":
    get:
      summary: 특정 my_info를 조회
      tags:
      - MyInfos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: 특정 my_info를 조회
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/MyInfo"
        '404':
          description: my_info를 찾을 수 없을 경우 오류 메시지를 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
    delete:
      summary: my_info 삭제
      tags:
      - MyInfos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: my_info 삭제
        '404':
          description: my_info를 찾을 수 없을 경우 오류 메시지를 반환
  "/my_infos/{id}/answer":
    get:
      summary: 특정 my_info의 답변을 조회
      tags:
      - MyInfos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: 특정 my_info의 답변을 조회
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  answer:
                    type: string
                required:
                - id
                - answer
        '404':
          description: my_info를 찾을 수 없을 경우 오류 메시지를 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/my_infos/{id}/p_fields":
    get:
      summary: 상대방 정보 조회
      tags:
      - MyInfos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: 상대방 정보 조회
          content:
            application/json:
              schema:
                type: object
                properties:
                  pName:
                    type: string
                  pBirthday:
                    type: string
                    format: date
                  pBirthtime:
                    type: string
                  p_lunar_birthday:
                    type: object
                    properties:
                      year:
                        type: integer
                      month:
                        type: integer
                      day:
                        type: integer
                      is_leap_month:
                        type: boolean
                    required:
                    - year
                    - month
                    - day
                    - is_leap_month
                required:
                - pName
                - pBirthday
                - pBirthtime
                - p_lunar_birthday
        '404':
          description: my_info를 찾을 수 없을 경우 오류 메시지를 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/my_infos/{id}/non_p_fields":
    get:
      summary: 사용자 정보 조회
      tags:
      - MyInfos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: 사용자 정보 조회
          content:
            application/json:
              schema:
                type: object
                properties:
                  gender:
                    type: string
                  birthday:
                    type: string
                    format: date
                  birthtime:
                    type: string
                  user_id:
                    type: integer
                  user_lunar_birthday:
                    type: object
                    properties:
                      year:
                        type: integer
                      month:
                        type: integer
                      day:
                        type: integer
                      is_leap_month:
                        type: boolean
                    required:
                    - year
                    - month
                    - day
                    - is_leap_month
                required:
                - gender
                - birthday
                - birthtime
                - user_id
                - user_lunar_birthday
        '404':
          description: my_info를 찾을 수 없을 경우 오류 메시지를 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/my_infos/{id}/p_saju":
    get:
      summary: 특정 my_info의 p_saju를 조회
      tags:
      - MyInfos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: 특정 my_info의 p_saju를 조회
          content:
            application/json:
              schema:
                type: object
                properties:
                  pName:
                    type: string
                  p_saju:
                    type: string
                required:
                - pName
                - p_saju
        '404':
          description: my_info를 찾을 수 없을 경우 오류 메시지를 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/my_infos/{id}/user_saju":
    get:
      summary: 사용자 정보 조회
      tags:
      - MyInfos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: 사용자 정보 조회
          content:
            application/json:
              schema:
                type: object
                properties:
                  gender:
                    type: string
                  user_saju:
                    type: string
                required:
                - gender
                - user_saju
        '404':
          description: 사용자를 찾을 수 없는 경우 오류 반환
  "/contents/category/{category_id}":
    get:
      summary: 카테고리별로 모든 컨텐츠를 가져옵니다.
      tags:
      - Contents
      parameters:
      - name: category_id
        in: path
        description: Category ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: contents found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    subtitle:
                      type: string
                    description:
                      type: string
                    imagePath:
                      type: string
                    content:
                      type: string
                    clover:
                      type: integer
                  required:
                  - id
                  - title
                  - subtitle
                  - description
                  - imagePath
                  - content
                  - clover
        '404':
          description: category not found
          content:
            application/json:
              schema:
                type: object

                  error:
                    type: string
                required:
                - error
                  message:
                    type: string
  "/contents/{content_id}/reviews":
    parameters:
    - name: content_id
      in: path
      description: Content ID
      required: true
      schema:
        type: string
    get:
      summary: 해당 사주 컨텐츠의 리뷰 정보를 가져옵니다.
      tags:
      - Reviews
      responses:
        '200':
          description: 해당 컨텐츠의 리뷰를 가져옵니다.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    review:
                      type: string
                    author:
                      type: string
                    contentId:
                      type: string
                    authorId:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                  required:
                  - id
                  - review
                  - author
                  - contentId
                  - authorId
                  - created_at
                  - updated_at
        '404':
          description: 리뷰를 찾을 수 없습니다.
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
