---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/categories":
    get:
      summary: 카테고리 정보를 가져옵니다.
      tags:
      - Categories
      responses:
        '200':
          description: 카테고리 정보를 가져옵니다.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    icon:
                      type: string
                  required:
                  - id
                  - name
                  - icon
        '404':
          description: 카테고리를 찾을 수 없습니다.
  "/contents/popular":
    get:
      summary: 리뷰가 5개 이상인 컨텐츠 정보를 가져옵니다.
      tags:
      - Contents
      responses:
        '200':
          description: 리뷰가 5개 이상인 컨텐츠를 가져옵니다.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    subtitle:
                      type: string
                    description:
                      type: string
                    imagePath:
                      type: string
                    content:
                      type: string
                    clover:
                      type: integer
                    reviews_count:
                      type: integer
                  required:
                  - id
                  - title
                  - imagePath
                  - content
                  - clover
        '404':
          description: 리뷰가 5개 이상인 컨텐츠가 없습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  "/contents/category/{category_id}/reviews":
    get:
      summary: 카테고리별 인기 많은 순으로 컨텐츠를 가져옵니다.
      tags:
      - Contents
      parameters:
      - name: category_id
        in: path
        description: Category ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: contents found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    subtitle:
                      type: string
                    description:
                      type: string
                    imagePath:
                      type: string
                    content:
                      type: string
                    clover:
                      type: integer
                    review_count:
                      type: integer
                  required:
                  - id
                  - title
                  - subtitle
                  - description
                  - imagePath
                  - content
                  - clover
                  - review_count
        '404':
          description: category not found
  "/contents/{id}":
    get:
      summary: 특정 컨텐츠 정보를 가져옵니다.
      tags:
      - Contents
      parameters:
      - name: id
        in: path
        description: Content ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: content found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  subtitle:
                    type: string
                  description:
                    type: string
                  imagePath:
                    type: string
                  content:
                    type: string
                  clover:
                    type: integer
                required:
                - id
                - title
                - imagePath
                - content
                - clover
        '404':
          description: content not found
  "/contents/reviews":
    get:
      summary: 전체 컨텐츠를 리뷰 수 기준으로 가져옵니다.
      tags:
      - Contents
      responses:
        '200':
          description: 정렬된 컨텐츠를 가져옵니다.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    subtitle:
                      type: string
                    description:
                      type: string
                    imagePath:
                      type: string
                    content:
                      type: string
                    clover:
                      type: integer
                    review_count:
                      type: integer
                  required:
                  - id
                  - title
                  - subtitle
                  - description
                  - imagePath
                  - content
                  - clover
                  - review_count
        '404':
          description: 콘텐츠가 없습니다.
  "/contents/category/{category_id}":
    get:
      summary: 카테고리별로 모든 컨텐츠를 가져옵니다.
      tags:
      - Contents
      parameters:
      - name: category_id
        in: path
        description: Category ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: contents found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    subtitle:
                      type: string
                    description:
                      type: string
                    imagePath:
                      type: string
                    content:
                      type: string
                    clover:
                      type: integer
                  required:
                  - id
                  - title
                  - subtitle
                  - description
                  - imagePath
                  - content
                  - clover
        '404':
          description: category not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  "/contents/{content_id}/reviews":
    parameters:
    - name: content_id
      in: path
      description: Content ID
      required: true
      schema:
        type: string
    get:
      summary: 해당 사주 컨텐츠의 리뷰 정보를 가져옵니다.
      tags:
      - Reviews
      responses:
        '200':
          description: 해당 컨텐츠의 리뷰를 가져옵니다.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    review:
                      type: string
                    author:
                      type: string
                    contentId:
                      type: string
                    authorId:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                  required:
                  - id
                  - review
                  - author
                  - contentId
                  - authorId
                  - created_at
                  - updated_at
        '404':
          description: 리뷰를 찾을 수 없습니다.
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
