default: &default
  adapter: <%= ENV.fetch("DATABASE_ADAPTER") %>
  pool: <%= ENV.fetch("DATABASE_POOL") %>
  encoding: <%= ENV.fetch("DATABASE_ENCODING") %>
  timeout: <%= ENV.fetch("DATABASE_TIMEOUT") %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>

development:
  <<: *default
  database: mytarot

test:
  <<: *default
  database: mytarot

production:
  <<: *default
  database: mytarot
